### ISSUE TITLE
Falha no Parser

### ISSUE THREAD

**Issue by brunohpg** [JoaoAugustoMV/API_BaseCAEPI#2]
Boa tarde.

Primeiramente, obrigado por seu trabalho.

Estou instanciando um container com a imagem publicada no docker hub, mas está com uma falha ao iniciar.
Aparentemente o arquivo de CA está com algum defeito e o algoritmo não consegue dar parse em uma linha.

```
Aguarde o download...
Download concluido!
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/fastapi/main.py", line 3, in <module>
    from routers import certificadoApovacao
  File "/fastapi/routers/certificadoApovacao.py", line 16, in <module>
    caService  = CAService()
  File "/fastapi/Services/CAService.py", line 9, in __init__
    self.baseDadosDF = BaseDadosCaEPI().retornarBaseDados()
  File "/fastapi/Services/BaseDadosCaEPI.py", line 44, in retornarBaseDados
    self._transformarEmDataFrame()
  File "/fastapi/Services/BaseDadosCaEPI.py", line 35, in _transformarEmDataFrame
    self.baseDadosDF = pd.read_csv(self.nomeArquivo, sep=r"(?<!:\s)\|(?!\s)",engine='python', encoding='unicode_escape', quoting=3, quotechar='"', dtype="string")
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/python_parser.py", line 290, in read
    alldata = self._rows_to_cols(content)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/python_parser.py", line 1053, in _rows_to_cols
    self._alert_malformed(msg, row_num + 1)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/python_parser.py", line 774, in _alert_malformed
    raise ParserError(msg)
pandas.errors.ParserError: Expected 19 fields in line 87474, saw 20
```

Eu baixei o arquivo e vi que o conteúdo era separado por pipe `|`. Fiz uma validação rápida e a linha em questão está com 18. Acho que o regex está quebrando em algum outro local.

Vlw

**Comment by JoaoAugustoMV** [comment]
Boa tarde, Bruno

Vou dar uma olhada. Agradeço o aviso!

**Comment by brunohpg** [comment]
O erro é na inicialização.
O container morre junto com o erro.

**Comment by JoaoAugustoMV** [comment]
Boa tarde Bruno,

Subi atualizei a img do docker.
Pode testar com o comando: docker run -d -p 5200:80 --name container-api-base-ca joaoaugustomv/api_base_ca_epi:2.0

Espero que não ocorra mais erros, mas se acontecer pode me avisar, que tentarei corrigir.

Vlw

**Comment by brunohpg** [comment]
Funionou corretamente.
Obrigado.

Só outro ponto, o swagger não entrou.

**Comment by JoaoAugustoMV** [comment]
Tenta "/docs"

**Comment by brunohpg** [comment]
> Tenta "/docs"

Isso funciona. Obrigado.
